version: '3'
services:
  react-app:
    container_name: web-app
    build: . 
    ports:
      - "8080:80"
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
    stdin_open: true
  tests:
    container_name: test-react-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
    command: ["npm", "run", "test"]